version: "3"

name: sql-server

services:
  sql-server:
    container_name: sql-server-db
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
      MSSQL_COLLATION: "Latin1_General_100_CI_AS_SC"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: